"""
Writes requirements.lock: exact versions of every package the robot's code
needs, read from a working venv.

Starts from the third-party modules that the runtime files import, maps them
to their distributions, and follows each distribution's requirements through
what is installed. Packages that are installed but not reachable this way
(old experiments, unused SDKs) are left out.

PyTorch is pinned to the CPU build: the boards have no NVIDIA GPU, and the
CUDA build pulls in several GB of NVIDIA libraries.

Run from Baymax-main with the venv you want to lock:
    venv/bin/python deploy/make_lock.py > requirements.lock
"""
import ast
import importlib.metadata as md
import platform
import sys
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

APP_DIR = Path(__file__).resolve().parent.parent

RUNTIME_FILES = [
    "realtime_gemini_10.py",
    "baymax_app.py",
    "baymax_cloud.py",
    "baymax_agent.py",
    "voice_analyzer.py",
    "semantic_embedder.py",
    "device_config.py",
    "fall_detection/detector.py",
]

# Needed at runtime but never imported by name.
EXTRA_ROOTS = {
    "onnxruntime": [],                     # backend for optimum's ORTModel (semantic memory)
    "en_core_web_sm": [],                  # spaCy model, loaded with spacy.load()
}

# Only the CUDA build of torch needs these.
CUDA_ONLY_PREFIXES = ("nvidia-", "cuda-")
CUDA_ONLY = {"triton"}

TORCH_CPU_INDEX = "https://download.pytorch.org/whl/cpu"
SPACY_MODEL_URL = ("https://github.com/explosion/spacy-models/releases/download/"
                   "en_core_web_sm-{v}/en_core_web_sm-{v}-py3-none-any.whl")


def imported_top_level_modules():
    local = {p.stem for p in APP_DIR.glob("*.py")} | {"fall_detection"}
    names = set()
    for rel in RUNTIME_FILES:
        tree = ast.parse((APP_DIR / rel).read_text())
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
                names.add(node.module.split(".")[0])
    return {n for n in names if n not in sys.stdlib_module_names and n not in local}


def root_distributions():
    by_module = md.packages_distributions()
    roots = {}
    for module in sorted(imported_top_level_modules()):
        dists = by_module.get(module)
        if not dists:
            sys.exit(f"no installed distribution provides module {module!r}")
        for dist in dists:
            roots.setdefault(canonicalize_name(dist), [])
    for name, extras in EXTRA_ROOTS.items():
        roots.setdefault(canonicalize_name(name), extras)
    return roots


def closure(roots):
    env = default_environment()
    seen = {}
    queue = list(roots.items())
    while queue:
        name, extras = queue.pop()
        dist = md.distribution(name)
        key = canonicalize_name(dist.metadata["Name"])
        if key in seen and set(extras) <= seen[key][1]:
            continue
        seen[key] = (dist, set(extras) | (seen[key][1] if key in seen else set()))
        for line in dist.requires or []:
            req = Requirement(line)
            if req.marker:
                wanted = [""] + list(extras)
                if not any(req.marker.evaluate({**env, "extra": e}) for e in wanted):
                    continue
            queue.append((canonicalize_name(req.name), list(req.extras)))
    return seen


def main():
    deps = closure(root_distributions())
    lines = []
    for key in sorted(deps):
        if key in CUDA_ONLY or key.startswith(CUDA_ONLY_PREFIXES):
            continue
        version = deps[key][0].version
        if key == "torch":
            lines.append(f"torch=={version.split('+')[0]}+cpu")
        elif key == "en-core-web-sm":
            lines.append(f"en_core_web_sm @ {SPACY_MODEL_URL.format(v=version)}")
        else:
            lines.append(f"{deps[key][0].metadata['Name']}=={version}")

    print(f"# Generated by deploy/make_lock.py from a working venv. Do not edit by hand.")
    print(f"# Python {platform.python_version()}, {platform.machine()} Linux. "
          f"Install with: pip install -r requirements.lock")
    print(f"--extra-index-url {TORCH_CPU_INDEX}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
